/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PastBoardMembersRouteImport } from './routes/past-board-members'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MembersRouteImport } from './routes/members'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComplaintRouteImport } from './routes/complaint'
import { Route as BranchBoardRouteImport } from './routes/branch-board'
import { Route as BoardMembersRouteImport } from './routes/board-members'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIdRouteImport } from './routes/news_.$id'
import { Route as EventsIdRouteImport } from './routes/events_.$id'
import { Route as BranchBoardBranchRouteImport } from './routes/branch-board.$branch'
import { Route as BlogIdRouteImport } from './routes/blog_.$id'
import { Route as AdminEventsRouteImport } from './routes/admin/events'

const PastBoardMembersRoute = PastBoardMembersRouteImport.update({
  id: '/past-board-members',
  path: '/past-board-members',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintRoute = ComplaintRouteImport.update({
  id: '/complaint',
  path: '/complaint',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchBoardRoute = BranchBoardRouteImport.update({
  id: '/branch-board',
  path: '/branch-board',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardMembersRoute = BoardMembersRouteImport.update({
  id: '/board-members',
  path: '/board-members',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIdRoute = NewsIdRouteImport.update({
  id: '/news_/$id',
  path: '/news/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events_/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchBoardBranchRoute = BranchBoardBranchRouteImport.update({
  id: '/$branch',
  path: '/$branch',
  getParentRoute: () => BranchBoardRoute,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/blog_/$id',
  path: '/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/board-members': typeof BoardMembersRoute
  '/branch-board': typeof BranchBoardRouteWithChildren
  '/complaint': typeof ComplaintRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/news': typeof NewsRoute
  '/past-board-members': typeof PastBoardMembersRoute
  '/admin/events': typeof AdminEventsRoute
  '/blog/$id': typeof BlogIdRoute
  '/branch-board/$branch': typeof BranchBoardBranchRoute
  '/events/$id': typeof EventsIdRoute
  '/news/$id': typeof NewsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/board-members': typeof BoardMembersRoute
  '/branch-board': typeof BranchBoardRouteWithChildren
  '/complaint': typeof ComplaintRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/news': typeof NewsRoute
  '/past-board-members': typeof PastBoardMembersRoute
  '/admin/events': typeof AdminEventsRoute
  '/blog/$id': typeof BlogIdRoute
  '/branch-board/$branch': typeof BranchBoardBranchRoute
  '/events/$id': typeof EventsIdRoute
  '/news/$id': typeof NewsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/board-members': typeof BoardMembersRoute
  '/branch-board': typeof BranchBoardRouteWithChildren
  '/complaint': typeof ComplaintRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/news': typeof NewsRoute
  '/past-board-members': typeof PastBoardMembersRoute
  '/admin/events': typeof AdminEventsRoute
  '/blog_/$id': typeof BlogIdRoute
  '/branch-board/$branch': typeof BranchBoardBranchRoute
  '/events_/$id': typeof EventsIdRoute
  '/news_/$id': typeof NewsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/board-members'
    | '/branch-board'
    | '/complaint'
    | '/contact'
    | '/events'
    | '/login'
    | '/members'
    | '/news'
    | '/past-board-members'
    | '/admin/events'
    | '/blog/$id'
    | '/branch-board/$branch'
    | '/events/$id'
    | '/news/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/board-members'
    | '/branch-board'
    | '/complaint'
    | '/contact'
    | '/events'
    | '/login'
    | '/members'
    | '/news'
    | '/past-board-members'
    | '/admin/events'
    | '/blog/$id'
    | '/branch-board/$branch'
    | '/events/$id'
    | '/news/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/board-members'
    | '/branch-board'
    | '/complaint'
    | '/contact'
    | '/events'
    | '/login'
    | '/members'
    | '/news'
    | '/past-board-members'
    | '/admin/events'
    | '/blog_/$id'
    | '/branch-board/$branch'
    | '/events_/$id'
    | '/news_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRoute
  BoardMembersRoute: typeof BoardMembersRoute
  BranchBoardRoute: typeof BranchBoardRouteWithChildren
  ComplaintRoute: typeof ComplaintRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  LoginRoute: typeof LoginRoute
  MembersRoute: typeof MembersRoute
  NewsRoute: typeof NewsRoute
  PastBoardMembersRoute: typeof PastBoardMembersRoute
  BlogIdRoute: typeof BlogIdRoute
  EventsIdRoute: typeof EventsIdRoute
  NewsIdRoute: typeof NewsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/past-board-members': {
      id: '/past-board-members'
      path: '/past-board-members'
      fullPath: '/past-board-members'
      preLoaderRoute: typeof PastBoardMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaint': {
      id: '/complaint'
      path: '/complaint'
      fullPath: '/complaint'
      preLoaderRoute: typeof ComplaintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch-board': {
      id: '/branch-board'
      path: '/branch-board'
      fullPath: '/branch-board'
      preLoaderRoute: typeof BranchBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board-members': {
      id: '/board-members'
      path: '/board-members'
      fullPath: '/board-members'
      preLoaderRoute: typeof BoardMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news_/$id': {
      id: '/news_/$id'
      path: '/news/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events_/$id': {
      id: '/events_/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch-board/$branch': {
      id: '/branch-board/$branch'
      path: '/$branch'
      fullPath: '/branch-board/$branch'
      preLoaderRoute: typeof BranchBoardBranchRouteImport
      parentRoute: typeof BranchBoardRoute
    }
    '/blog_/$id': {
      id: '/blog_/$id'
      path: '/blog/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminEventsRoute: typeof AdminEventsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEventsRoute: AdminEventsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BranchBoardRouteChildren {
  BranchBoardBranchRoute: typeof BranchBoardBranchRoute
}

const BranchBoardRouteChildren: BranchBoardRouteChildren = {
  BranchBoardBranchRoute: BranchBoardBranchRoute,
}

const BranchBoardRouteWithChildren = BranchBoardRoute._addFileChildren(
  BranchBoardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRoute,
  BoardMembersRoute: BoardMembersRoute,
  BranchBoardRoute: BranchBoardRouteWithChildren,
  ComplaintRoute: ComplaintRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  LoginRoute: LoginRoute,
  MembersRoute: MembersRoute,
  NewsRoute: NewsRoute,
  PastBoardMembersRoute: PastBoardMembersRoute,
  BlogIdRoute: BlogIdRoute,
  EventsIdRoute: EventsIdRoute,
  NewsIdRoute: NewsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
